import type { GuruProfile } from "@/types";

/**
 * 투자 구루 프로필 데이터
 */
export const GURU_PROFILES: GuruProfile[] = [
  {
    id: "buffett",
    name: "Warren Buffett",
    nameKo: "워렌 버핏",
    nameJa: "ウォーレン・バフェット",
    firm: "Berkshire Hathaway",
    idealAllocation: [
      { tag: "value", targetPercent: 40 },
      { tag: "dividend", targetPercent: 25 },
      { tag: "growth", targetPercent: 15 },
      { tag: "cash", targetPercent: 15 },
      { tag: "index", targetPercent: 5 },
    ],
  },
  {
    id: "munger",
    name: "Charlie Munger",
    nameKo: "찰리 멍거",
    nameJa: "チャーリー・マンガー",
    firm: "Daily Journal Corporation",
    idealAllocation: [
      { tag: "value", targetPercent: 50 },
      { tag: "growth", targetPercent: 20 },
      { tag: "dividend", targetPercent: 15 },
      { tag: "cash", targetPercent: 15 },
    ],
  },
  {
    id: "lynch",
    name: "Peter Lynch",
    nameKo: "피터 린치",
    nameJa: "ピーター・リンチ",
    firm: "Fidelity (Magellan Fund, ret.)",
    idealAllocation: [
      { tag: "growth", targetPercent: 45 },
      { tag: "value", targetPercent: 20 },
      { tag: "dividend", targetPercent: 15 },
      { tag: "index", targetPercent: 10 },
      { tag: "cash", targetPercent: 10 },
    ],
  },
  {
    id: "graham",
    name: "Benjamin Graham",
    nameKo: "벤저민 그레이엄",
    nameJa: "ベンジャミン・グレアム",
    firm: "Graham-Newman Corp. (hist.)",
    idealAllocation: [
      { tag: "value", targetPercent: 40 },
      { tag: "bond", targetPercent: 25 },
      { tag: "dividend", targetPercent: 20 },
      { tag: "cash", targetPercent: 15 },
    ],
  },
  {
    id: "dalio",
    name: "Ray Dalio",
    nameKo: "레이 달리오",
    nameJa: "レイ・ダリオ",
    firm: "Bridgewater Associates",
    idealAllocation: [
      { tag: "bond", targetPercent: 40 },
      { tag: "index", targetPercent: 20 },
      { tag: "commodity", targetPercent: 15 },
      { tag: "dividend", targetPercent: 10 },
      { tag: "growth", targetPercent: 10 },
      { tag: "cash", targetPercent: 5 },
    ],
  },
  {
    id: "lilu",
    name: "Li Lu",
    nameKo: "리루",
    nameJa: "リー・ルー",
    firm: "Himalaya Capital",

    idealAllocation: [
      { tag: "value", targetPercent: 45 },
      { tag: "growth", targetPercent: 25 },
      { tag: "dividend", targetPercent: 15 },
      { tag: "cash", targetPercent: 15 },
    ],
  },
  {
    id: "ackman",
    name: "Bill Ackman",
    nameKo: "빌 애크먼",
    nameJa: "ビル・アックマン",
    firm: "Pershing Square Capital",
    idealAllocation: [
      { tag: "value", targetPercent: 35 },
      { tag: "growth", targetPercent: 30 },
      { tag: "dividend", targetPercent: 15 },
      { tag: "cash", targetPercent: 15 },
      { tag: "bond", targetPercent: 5 },
    ],
  },
  {
    id: "burry",
    name: "Michael Burry",
    nameKo: "마이클 버리",
    nameJa: "マイケル・バーリー",
    firm: "Scion Asset Management",
    idealAllocation: [
      { tag: "value", targetPercent: 40 },
      { tag: "commodity", targetPercent: 20 },
      { tag: "cash", targetPercent: 20 },
      { tag: "growth", targetPercent: 10 },
      { tag: "bond", targetPercent: 10 },
    ],
  },
  {
    id: "fisher",
    name: "Ken Fisher",
    nameKo: "켄 피셔",
    nameJa: "ケン・フィッシャー",
    firm: "Fisher Asset Management",
    idealAllocation: [
      { tag: "growth", targetPercent: 40 },
      { tag: "index", targetPercent: 25 },
      { tag: "dividend", targetPercent: 15 },
      { tag: "value", targetPercent: 10 },
      { tag: "cash", targetPercent: 10 },
    ],
  },
  {
    id: "cohen",
    name: "Steven Cohen",
    nameKo: "스티븐 코헨",
    nameJa: "スティーブン・コーエン",
    firm: "Point72 Asset Management",
    idealAllocation: [
      { tag: "growth", targetPercent: 30 },
      { tag: "value", targetPercent: 25 },
      { tag: "index", targetPercent: 15 },
      { tag: "cash", targetPercent: 15 },
      { tag: "commodity", targetPercent: 10 },
      { tag: "bond", targetPercent: 5 },
    ],
  },
  {
    id: "marks",
    name: "Howard Marks",
    nameKo: "하워드 막스",
    nameJa: "ハワード・マークス",
    firm: "Oaktree Capital Management",
    idealAllocation: [
      { tag: "bond", targetPercent: 35 },
      { tag: "value", targetPercent: 30 },
      { tag: "cash", targetPercent: 15 },
      { tag: "dividend", targetPercent: 10 },
      { tag: "growth", targetPercent: 10 },
    ],
  },
  {
    id: "klarman",
    name: "Seth Klarman",
    nameKo: "세스 클라먼",
    nameJa: "セス・クラーマン",
    firm: "The Baupost Group",
    idealAllocation: [
      { tag: "value", targetPercent: 40 },
      { tag: "cash", targetPercent: 25 },
      { tag: "bond", targetPercent: 20 },
      { tag: "dividend", targetPercent: 10 },
      { tag: "growth", targetPercent: 5 },
    ],
  },
  {
    id: "templeton",
    name: "John Templeton",
    nameKo: "존 템플턴",
    nameJa: "ジョン・テンプルトン",
    firm: "Templeton Growth Fund (hist.)",
    idealAllocation: [
      { tag: "value", targetPercent: 40 },
      { tag: "index", targetPercent: 20 },
      { tag: "growth", targetPercent: 15 },
      { tag: "bond", targetPercent: 15 },
      { tag: "cash", targetPercent: 10 },
    ],
  },
  {
    id: "soros",
    name: "George Soros",
    nameKo: "조지 소로스",
    nameJa: "ジョージ・ソロス",
    firm: "Soros Fund Management",
    idealAllocation: [
      { tag: "growth", targetPercent: 30 },
      { tag: "bond", targetPercent: 20 },
      { tag: "commodity", targetPercent: 20 },
      { tag: "cash", targetPercent: 15 },
      { tag: "index", targetPercent: 15 },
    ],
  },
  {
    id: "wood",
    name: "Cathie Wood",
    nameKo: "캐시 우드",
    nameJa: "キャシー・ウッド",
    firm: "ARK Invest",
    idealAllocation: [
      { tag: "growth", targetPercent: 55 },
      { tag: "crypto", targetPercent: 15 },
      { tag: "index", targetPercent: 10 },
      { tag: "cash", targetPercent: 10 },
      { tag: "value", targetPercent: 10 },
    ],
  },
  {
    id: "druckenmiller",
    name: "Stanley Druckenmiller",
    nameKo: "스탠리 드러큰밀러",
    nameJa: "スタンリー・ドラッケンミラー",
    firm: "Duquesne Family Office",

    idealAllocation: [
      { tag: "growth", targetPercent: 35 },
      { tag: "index", targetPercent: 20 },
      { tag: "commodity", targetPercent: 20 },
      { tag: "cash", targetPercent: 15 },
      { tag: "bond", targetPercent: 10 },
    ],
  },
  {
    id: "smith",
    name: "Terry Smith",
    nameKo: "테리 스미스",
    nameJa: "テリー・スミス",
    firm: "Fundsmith LLP",
    idealAllocation: [
      { tag: "growth", targetPercent: 45 },
      { tag: "dividend", targetPercent: 25 },
      { tag: "value", targetPercent: 20 },
      { tag: "cash", targetPercent: 10 },
    ],
  },
  {
    id: "greenblatt",
    name: "Joel Greenblatt",
    nameKo: "조엘 그린블라트",
    nameJa: "ジョエル・グリーンブラット",
    firm: "Gotham Asset Management",
    idealAllocation: [
      { tag: "value", targetPercent: 40 },
      { tag: "growth", targetPercent: 25 },
      { tag: "index", targetPercent: 20 },
      { tag: "cash", targetPercent: 10 },
      { tag: "bond", targetPercent: 5 },
    ],
  },
];

/**
 * 구루 ID로 프로필 조회
 */
export function getGuruProfile(id: string): GuruProfile | undefined {
  return GURU_PROFILES.find((g) => g.id === id);
}
