import type { AssetFormData } from "@/types";

/**
 * 온보딩 데모용 샘플 자산 데이터
 * 현금(JPY/KRW/USD) + 일본·한국·미국 주식/ETF 각 5종목
 * 종목당 평가액 500~1000만원 기준 (2026년 5월 기준 시세)
 */
export const SAMPLE_ASSETS: AssetFormData[] = [
  // ── 현금 (각 100~300만원) ─────────────────────────────────
  {
    name: "엔화 예금",
    ticker: undefined,
    type: "cash",
    market: "JP",
    currency: "JPY",
    quantity: 200000,
    avgBuyPrice: 1,
    currentPrice: 1,
    categories: ["cash"],
    memo: "샘플 데이터",
  },
  {
    name: "원화 예금",
    ticker: undefined,
    type: "cash",
    market: "KR",
    currency: "KRW",
    quantity: 2000000,
    avgBuyPrice: 1,
    currentPrice: 1,
    categories: ["cash"],
    memo: "샘플 데이터",
  },
  {
    name: "달러 예금",
    ticker: undefined,
    type: "cash",
    market: "US",
    currency: "USD",
    quantity: 1500,
    avgBuyPrice: 1,
    currentPrice: 1,
    categories: ["cash"],
    memo: "샘플 데이터",
  },
  // ── 일본 주식/ETF (종목당 ~600만원 / 1 JPY ≈ 9.1 KRW) ───
  {
    name: "トヨタ自動車",
    ticker: "7203.T",
    type: "stock",
    market: "JP",
    currency: "JPY",
    quantity: 200,
    avgBuyPrice: 3100,
    currentPrice: 3450,
    categories: ["value", "dividend"],
    memo: "샘플 데이터",
  },
  {
    name: "ソニーグループ",
    ticker: "6758.T",
    type: "stock",
    market: "JP",
    currency: "JPY",
    quantity: 250,
    avgBuyPrice: 2400,
    currentPrice: 2750,
    categories: ["growth"],
    memo: "샘플 데이터",
  },
  {
    name: "日本電信電話",
    ticker: "9432.T",
    type: "stock",
    market: "JP",
    currency: "JPY",
    quantity: 4000,
    avgBuyPrice: 148,
    currentPrice: 165,
    categories: ["dividend"],
    memo: "샘플 데이터",
  },
  {
    name: "信越化学工業",
    ticker: "4063.T",
    type: "stock",
    market: "JP",
    currency: "JPY",
    quantity: 100,
    avgBuyPrice: 5600,
    currentPrice: 6200,
    categories: ["growth", "value"],
    memo: "샘플 데이터",
  },
  {
    name: "NEXT FUNDS TOPIX連動型ETF",
    ticker: "1306.T",
    type: "etf",
    market: "JP",
    currency: "JPY",
    quantity: 300,
    avgBuyPrice: 2000,
    currentPrice: 2300,
    categories: ["index"],
    memo: "샘플 데이터",
  },
  // ── 한국 주식/ETF (종목당 600~720만원) ────────────────────
  {
    name: "삼성전자",
    ticker: "005930.KS",
    type: "stock",
    market: "KR",
    currency: "KRW",
    quantity: 100,
    avgBuyPrice: 65000,
    currentPrice: 72000,
    categories: ["value", "dividend"],
    memo: "샘플 데이터",
  },
  {
    name: "SK하이닉스",
    ticker: "000660.KS",
    type: "stock",
    market: "KR",
    currency: "KRW",
    quantity: 30,
    avgBuyPrice: 180000,
    currentPrice: 210000,
    categories: ["growth"],
    memo: "샘플 데이터",
  },
  {
    name: "NAVER",
    ticker: "035420.KS",
    type: "stock",
    market: "KR",
    currency: "KRW",
    quantity: 35,
    avgBuyPrice: 220000,
    currentPrice: 185000,
    categories: ["growth"],
    memo: "샘플 데이터",
  },
  {
    name: "카카오",
    ticker: "035720.KS",
    type: "stock",
    market: "KR",
    currency: "KRW",
    quantity: 150,
    avgBuyPrice: 58000,
    currentPrice: 42000,
    categories: ["growth"],
    memo: "샘플 데이터",
  },
  {
    name: "KODEX 200",
    ticker: "069500.KS",
    type: "etf",
    market: "KR",
    currency: "KRW",
    quantity: 250,
    avgBuyPrice: 24500,
    currentPrice: 27500,
    categories: ["index"],
    memo: "샘플 데이터",
  },
  // ── 미국 주식/ETF (종목당 ~$3,600~5,760 / 1 USD ≈ 1,380 KRW) ──
  {
    name: "Apple Inc.",
    ticker: "AAPL",
    type: "stock",
    market: "US",
    currency: "USD",
    quantity: 25,
    avgBuyPrice: 185,
    currentPrice: 213,
    categories: ["growth"],
    memo: "샘플 데이터",
  },
  {
    name: "Microsoft Corp.",
    ticker: "MSFT",
    type: "stock",
    market: "US",
    currency: "USD",
    quantity: 12,
    avgBuyPrice: 400,
    currentPrice: 432,
    categories: ["growth"],
    memo: "샘플 데이터",
  },
  {
    name: "NVIDIA Corp.",
    ticker: "NVDA",
    type: "stock",
    market: "US",
    currency: "USD",
    quantity: 50,
    avgBuyPrice: 90,
    currentPrice: 120,
    categories: ["growth"],
    memo: "샘플 데이터",
  },
  {
    name: "Vanguard S&P 500 ETF",
    ticker: "VOO",
    type: "etf",
    market: "US",
    currency: "USD",
    quantity: 10,
    avgBuyPrice: 510,
    currentPrice: 545,
    categories: ["index"],
    memo: "샘플 데이터",
  },
  {
    name: "Berkshire Hathaway B",
    ticker: "BRK-B",
    type: "stock",
    market: "US",
    currency: "USD",
    quantity: 12,
    avgBuyPrice: 440,
    currentPrice: 480,
    categories: ["value"],
    memo: "샘플 데이터",
  },
];
