import type { AssetFormData } from "@/types";

/**
 * 온보딩 데모용 샘플 자산 데이터
 * 한국, 미국, 일본 시장을 아우르는 15개 자산으로 구성
 */
export const SAMPLE_ASSETS: AssetFormData[] = [
  {
    name: "삼성전자",
    ticker: "005930.KS",
    type: "stock",
    market: "KR",
    currency: "KRW",
    quantity: 50,
    avgBuyPrice: 68000,
    currentPrice: 71500,
    categories: ["value"],
    memo: "샘플 데이터",
  },
  {
    name: "Apple Inc.",
    ticker: "AAPL",
    type: "stock",
    market: "US",
    currency: "USD",
    quantity: 10,
    avgBuyPrice: 178,
    currentPrice: 193,
    categories: ["growth"],
    memo: "샘플 데이터",
  },
  {
    name: "SPDR S&P 500 ETF Trust",
    ticker: "SPY",
    type: "etf",
    market: "US",
    currency: "USD",
    quantity: 5,
    avgBuyPrice: 450,
    currentPrice: 472,
    categories: ["index"],
    memo: "샘플 데이터",
  },
  {
    name: "달러 예금",
    ticker: undefined,
    type: "cash",
    market: "US",
    currency: "USD",
    quantity: 3000,
    avgBuyPrice: 1,
    currentPrice: 1,
    categories: ["cash"],
    memo: "샘플 데이터",
  },
  {
    name: "원화 예금",
    ticker: undefined,
    type: "cash",
    market: "KR",
    currency: "KRW",
    quantity: 5000000,
    avgBuyPrice: 1,
    currentPrice: 1,
    categories: ["cash"],
    memo: "샘플 데이터",
  },
  {
    name: "SK하이닉스",
    ticker: "000660.KS",
    type: "stock",
    market: "KR",
    currency: "KRW",
    quantity: 20,
    avgBuyPrice: 112000,
    currentPrice: 198000,
    categories: ["growth"],
    memo: "샘플 데이터",
  },
  {
    name: "NAVER",
    ticker: "035420.KS",
    type: "stock",
    market: "KR",
    currency: "KRW",
    quantity: 15,
    avgBuyPrice: 242000,
    currentPrice: 188000,
    categories: ["growth"],
    memo: "샘플 데이터",
  },
  {
    name: "KODEX 200",
    ticker: "069500.KS",
    type: "etf",
    market: "KR",
    currency: "KRW",
    quantity: 30,
    avgBuyPrice: 27500,
    currentPrice: 30200,
    categories: ["index"],
    memo: "샘플 데이터",
  },
  {
    name: "Microsoft Corp.",
    ticker: "MSFT",
    type: "stock",
    market: "US",
    currency: "USD",
    quantity: 8,
    avgBuyPrice: 385,
    currentPrice: 428,
    categories: ["growth"],
    memo: "샘플 데이터",
  },
  {
    name: "NVIDIA Corp.",
    ticker: "NVDA",
    type: "stock",
    market: "US",
    currency: "USD",
    quantity: 15,
    avgBuyPrice: 620,
    currentPrice: 1085,
    categories: ["growth"],
    memo: "샘플 데이터",
  },
  {
    name: "Amazon.com Inc.",
    ticker: "AMZN",
    type: "stock",
    market: "US",
    currency: "USD",
    quantity: 12,
    avgBuyPrice: 182,
    currentPrice: 224,
    categories: ["growth"],
    memo: "샘플 데이터",
  },
  {
    name: "Berkshire Hathaway B",
    ticker: "BRK-B",
    type: "stock",
    market: "US",
    currency: "USD",
    quantity: 10,
    avgBuyPrice: 358,
    currentPrice: 462,
    categories: ["value"],
    memo: "샘플 데이터",
  },
  {
    name: "Invesco QQQ Trust",
    ticker: "QQQ",
    type: "etf",
    market: "US",
    currency: "USD",
    quantity: 6,
    avgBuyPrice: 438,
    currentPrice: 518,
    categories: ["index"],
    memo: "샘플 데이터",
  },
  {
    name: "トヨタ自動車",
    ticker: "7203.T",
    type: "stock",
    market: "JP",
    currency: "JPY",
    quantity: 100,
    avgBuyPrice: 2580,
    currentPrice: 3450,
    categories: ["value", "dividend"],
    memo: "샘플 데이터",
  },
  {
    name: "ソニーグループ",
    ticker: "6758.T",
    type: "stock",
    market: "JP",
    currency: "JPY",
    quantity: 50,
    avgBuyPrice: 11200,
    currentPrice: 14600,
    categories: ["growth", "value"],
    memo: "샘플 데이터",
  },
];
