import type { Market } from "@/types";

/** 스크리닝용 최소 종목 정보 */
export interface UniverseStock {
  ticker: string;
  name: string;
  market: Market;
}

// ─── 시장별 종목 유니버스 ────────────────────────────────────────────────────────

const US: UniverseStock[] = [
  { ticker: "AAPL",  name: "Apple Inc.",              market: "US" },
  { ticker: "MSFT",  name: "Microsoft",               market: "US" },
  { ticker: "NVDA",  name: "NVIDIA",                  market: "US" },
  { ticker: "AMZN",  name: "Amazon",                  market: "US" },
  { ticker: "GOOGL", name: "Alphabet",                market: "US" },
  { ticker: "META",  name: "Meta Platforms",          market: "US" },
  { ticker: "TSLA",  name: "Tesla",                   market: "US" },
  { ticker: "BRK-B", name: "Berkshire Hathaway",      market: "US" },
  { ticker: "UNH",   name: "UnitedHealth Group",      market: "US" },
  { ticker: "LLY",   name: "Eli Lilly",               market: "US" },
  { ticker: "JPM",   name: "JPMorgan Chase",          market: "US" },
  { ticker: "AVGO",  name: "Broadcom",                market: "US" },
  { ticker: "V",     name: "Visa",                    market: "US" },
  { ticker: "MA",    name: "Mastercard",              market: "US" },
  { ticker: "JNJ",   name: "Johnson & Johnson",       market: "US" },
  { ticker: "PG",    name: "Procter & Gamble",        market: "US" },
  { ticker: "HD",    name: "Home Depot",              market: "US" },
  { ticker: "XOM",   name: "ExxonMobil",              market: "US" },
  { ticker: "ABBV",  name: "AbbVie",                  market: "US" },
  { ticker: "MRK",   name: "Merck",                   market: "US" },
  { ticker: "PEP",   name: "PepsiCo",                 market: "US" },
  { ticker: "KO",    name: "Coca-Cola",               market: "US" },
  { ticker: "COST",  name: "Costco",                  market: "US" },
  { ticker: "WMT",   name: "Walmart",                 market: "US" },
  { ticker: "ADBE",  name: "Adobe",                   market: "US" },
  { ticker: "NFLX",  name: "Netflix",                 market: "US" },
  { ticker: "AMD",   name: "AMD",                     market: "US" },
  { ticker: "ORCL",  name: "Oracle",                  market: "US" },
  { ticker: "CRM",   name: "Salesforce",              market: "US" },
  { ticker: "NOW",   name: "ServiceNow",              market: "US" },
  { ticker: "INTU",  name: "Intuit",                  market: "US" },
  { ticker: "ACN",   name: "Accenture",               market: "US" },
  { ticker: "TXN",   name: "Texas Instruments",       market: "US" },
  { ticker: "QCOM",  name: "Qualcomm",                market: "US" },
  { ticker: "MU",    name: "Micron Technology",       market: "US" },
  { ticker: "AMAT",  name: "Applied Materials",       market: "US" },
  { ticker: "LRCX",  name: "Lam Research",            market: "US" },
  { ticker: "PANW",  name: "Palo Alto Networks",      market: "US" },
  { ticker: "CRWD",  name: "CrowdStrike",             market: "US" },
  { ticker: "DDOG",  name: "Datadog",                 market: "US" },
  { ticker: "NET",   name: "Cloudflare",              market: "US" },
  { ticker: "SHOP",  name: "Shopify",                 market: "US" },
  { ticker: "UBER",  name: "Uber",                    market: "US" },
  { ticker: "PYPL",  name: "PayPal",                  market: "US" },
  { ticker: "PLTR",  name: "Palantir Technologies",   market: "US" },
  { ticker: "SNOW",  name: "Snowflake",               market: "US" },
  { ticker: "COIN",  name: "Coinbase",                market: "US" },
  { ticker: "SQ",    name: "Block (Square)",          market: "US" },
  { ticker: "RBLX",  name: "Roblox",                  market: "US" },
  { ticker: "RIVN",  name: "Rivian Automotive",       market: "US" },
];

const KR: UniverseStock[] = [
  { ticker: "005930.KS", name: "삼성전자",          market: "KR" },
  { ticker: "000660.KS", name: "SK하이닉스",        market: "KR" },
  { ticker: "035420.KS", name: "NAVER",             market: "KR" },
  { ticker: "005380.KS", name: "현대차",            market: "KR" },
  { ticker: "051910.KS", name: "LG화학",            market: "KR" },
  { ticker: "006400.KS", name: "삼성SDI",           market: "KR" },
  { ticker: "207940.KS", name: "삼성바이오로직스",   market: "KR" },
  { ticker: "068270.KS", name: "셀트리온",          market: "KR" },
  { ticker: "035720.KS", name: "카카오",            market: "KR" },
  { ticker: "066570.KS", name: "LG전자",            market: "KR" },
  { ticker: "003550.KS", name: "LG",               market: "KR" },
  { ticker: "030200.KS", name: "KT",               market: "KR" },
  { ticker: "017670.KS", name: "SK텔레콤",          market: "KR" },
  { ticker: "009150.KS", name: "삼성전기",          market: "KR" },
  { ticker: "047810.KS", name: "한국항공우주",      market: "KR" },
  { ticker: "086790.KS", name: "하나금융지주",      market: "KR" },
  { ticker: "316140.KS", name: "우리금융지주",      market: "KR" },
  { ticker: "000270.KS", name: "기아",             market: "KR" },
  { ticker: "055550.KS", name: "신한지주",          market: "KR" },
  { ticker: "373220.KS", name: "LG에너지솔루션",    market: "KR" },
  { ticker: "000100.KS", name: "유한양행",          market: "KR" },
  { ticker: "003490.KS", name: "대한항공",          market: "KR" },
  { ticker: "259960.KS", name: "크래프톤",          market: "KR" },
  { ticker: "036570.KS", name: "엔씨소프트",        market: "KR" },
  { ticker: "323410.KS", name: "카카오뱅크",        market: "KR" },
  { ticker: "293490.KQ", name: "카카오게임즈",       market: "KR" },
  { ticker: "263750.KQ", name: "펄어비스",          market: "KR" },
  { ticker: "094280.KQ", name: "HLB",              market: "KR" },
  { ticker: "145020.KQ", name: "휴젤",             market: "KR" },
  { ticker: "041510.KQ", name: "에스엠",            market: "KR" },
];

const JP: UniverseStock[] = [
  { ticker: "7203.T",  name: "トヨタ自動車",               market: "JP" },
  { ticker: "6758.T",  name: "ソニーグループ",              market: "JP" },
  { ticker: "9984.T",  name: "ソフトバンクG",              market: "JP" },
  { ticker: "9432.T",  name: "NTT",                      market: "JP" },
  { ticker: "7974.T",  name: "任天堂",                    market: "JP" },
  { ticker: "6861.T",  name: "キーエンス",                 market: "JP" },
  { ticker: "4519.T",  name: "中外製薬",                   market: "JP" },
  { ticker: "4568.T",  name: "第一三共",                   market: "JP" },
  { ticker: "9433.T",  name: "KDDI",                     market: "JP" },
  { ticker: "6954.T",  name: "ファナック",                  market: "JP" },
  { ticker: "7267.T",  name: "本田技研工業",               market: "JP" },
  { ticker: "6702.T",  name: "富士通",                    market: "JP" },
  { ticker: "8306.T",  name: "三菱UFJフィナンシャル",       market: "JP" },
  { ticker: "4661.T",  name: "オリエンタルランド",           market: "JP" },
  { ticker: "6367.T",  name: "ダイキン工業",               market: "JP" },
  { ticker: "2413.T",  name: "エムスリー",                 market: "JP" },
  { ticker: "4543.T",  name: "テルモ",                    market: "JP" },
  { ticker: "6501.T",  name: "日立製作所",                 market: "JP" },
  { ticker: "7741.T",  name: "HOYA",                     market: "JP" },
  { ticker: "6098.T",  name: "リクルートホールディングス",   market: "JP" },
  { ticker: "8035.T",  name: "東京エレクトロン",            market: "JP" },
  { ticker: "6920.T",  name: "レーザーテック",             market: "JP" },
  { ticker: "4063.T",  name: "信越化学工業",               market: "JP" },
  { ticker: "9843.T",  name: "ニトリホールディングス",       market: "JP" },
  { ticker: "6723.T",  name: "ルネサスエレクトロニクス",     market: "JP" },
  { ticker: "4578.T",  name: "大塚ホールディングス",        market: "JP" },
  { ticker: "3382.T",  name: "セブン&アイ・ホールディングス", market: "JP" },
  { ticker: "9022.T",  name: "東海旅客鉄道 (JR東海)",      market: "JP" },
  { ticker: "6503.T",  name: "三菱電機",                   market: "JP" },
  { ticker: "4307.T",  name: "野村総合研究所",             market: "JP" },
];

const EU: UniverseStock[] = [
  { ticker: "SAP.DE",    name: "SAP",                  market: "EU" },
  { ticker: "ASML.AS",   name: "ASML Holding",         market: "EU" },
  { ticker: "NOVN.SW",   name: "Novartis",             market: "EU" },
  { ticker: "NESN.SW",   name: "Nestlé",               market: "EU" },
  { ticker: "MC.PA",     name: "LVMH",                 market: "EU" },
  { ticker: "OR.PA",     name: "L'Oréal",              market: "EU" },
  { ticker: "ROG.SW",    name: "Roche",                market: "EU" },
  { ticker: "BAYN.DE",   name: "Bayer",                market: "EU" },
  { ticker: "DTE.DE",    name: "Deutsche Telekom",     market: "EU" },
  { ticker: "AIR.PA",    name: "Airbus",               market: "EU" },
  { ticker: "BNP.PA",    name: "BNP Paribas",          market: "EU" },
  { ticker: "TTE.PA",    name: "TotalEnergies",        market: "EU" },
  { ticker: "BMW.DE",    name: "BMW",                  market: "EU" },
  { ticker: "SIE.DE",    name: "Siemens",              market: "EU" },
  { ticker: "MUV2.DE",   name: "Munich Re",            market: "EU" },
  { ticker: "ALV.DE",    name: "Allianz",              market: "EU" },
  { ticker: "IFX.DE",    name: "Infineon Technologies", market: "EU" },
  { ticker: "ADYEN.AS",  name: "Adyen",                market: "EU" },
  { ticker: "HEIA.AS",   name: "Heineken",             market: "EU" },
  { ticker: "RMS.PA",    name: "Hermès",               market: "EU" },
  { ticker: "KER.PA",    name: "Kering",               market: "EU" },
  { ticker: "CAP.PA",    name: "Capgemini",            market: "EU" },
  { ticker: "PRX.AS",    name: "Prosus",               market: "EU" },
  { ticker: "STLA.MI",   name: "Stellantis",           market: "EU" },
  { ticker: "SAN.MC",    name: "Banco Santander",      market: "EU" },
];

export const STOCK_UNIVERSE: Record<Market, UniverseStock[]> = {
  US,
  KR,
  JP,
  EU,
  OTHER: [],
};

/** 선택한 시장의 유니버스 반환 (ALL = 전 시장 합산) */
export function getUniverse(market: "ALL" | Market): UniverseStock[] {
  if (market === "ALL") return [...US, ...KR, ...JP, ...EU];
  return STOCK_UNIVERSE[market] ?? [];
}
